routes/web.php
   $movies =  Movie::orderByUniqueViews()->get();
   $season =  Season::orderByUniqueViews()->get();
   return view('admin.viewtracker',compact('movies','season'));
 })->name('view.track');

  Route::get('/quick/change/status/{id}','QuickUpdateController@change')->name('quick.movie.status');

  Route::get('/quick/change/status/tvseries/{id}','QuickUpdateController@changetvstatus')->name('quick.tv.status');

  Route::get('/admin/pending/movie','MovieController@addedMovies')->name('addedmovies');

  Route::get('/admin/pending/tvshows','TvSeriesController@addedTvSeries')->name('addedTvSeries');

  Route::get('/admin/pending/livtvs','LiveTvController@addedLiveTv')->name('addedLiveTv');

  Route::resource('admin/blog', 'BlogController');
  
  Route::post('admin/blog/bulk_delete', 'BlogController@bulk_delete');
  
  Route::post('admin/blog/create', 'BlogController@create');
  
  Route::patch('admin/blog/update/{id}', 'BlogController@update');
  
  Route::delete('admin/blog/destroy/{id}', 'BlogController@destroy');

  Route::post('admin/movie/{id}/addsubtitle','SubtitleController@post')->name('add.subtitle');

  Route::post('admin/movie/{id}/delete/subtitle','SubtitleController@delete')->name('del.subtitle');

  Route::get('admin', 'DashboardController@dashboard')->name('dashboard');

  Route::get('admin/profile', function(){
    $auth = Auth::user();
    return view('admin.profile', compact('auth'));
  });

  Route::get('/admin/player-setting','PlayerSettingController@get')->name('player.set');
  Route::post('/admin/player-setting/update','PlayerSettingController@update')->name('player.update');

  Route::resource('admin/menu', 'MenuController');
  Route::post('admin/menu/bulk_delete', 'MenuController@bulk_delete');
  Route::post('admin/menu/reposition', 'MenuController@reposition')->name('menu_reposition');

  Route::resource('admin/users', 'UsersController');
  Route::get('admin/user/status/{id}','UsersController@changestatus');

  Route::get('user/subscription/{id}', 'UsersController@change_subscription_show')->name('change_subscription_show');
  Route::post('user/subscription', 'UsersController@change_subscription')->name('change_subscription');
  Route::post('admin/users/bulk_delete', 'UsersController@bulk_delete');
  Route::resource('admin/movies', 'MovieController');
  Route::get('admin/movie/upload_video/converting', 'MovieController@upload_video');
   Route::get('admin/tvshow/upload_video/converting', 'TvSeriesController@upload_video');
  Route::get('admin/movie/vimeoapi', 'MovieController@vimeoApicall');
  
  Route::get('admin/movies/tmdb/translations', 'MovieController@tmdb_translations')->name('tmdb_movie_translate');
  Route::post('admin/movies/bulk_delete', 'MovieController@bulk_delete');

  // live tv routes
  Route::resource('admin/livetv', 'LiveTvController');
  Route::get('admin/livetv/upload_video/converting', 'LiveTvController@upload_video');
  Route::get('admin/livetv/vimeoapi', 'LiveTvController@vimeoApicall');
  
  Route::get('admin/livetv/tmdb/translations', 'LiveTvController@tmdb_translations')->name('tmdb_movie_translate');
  Route::post('admin/livetv/bulk_delete', 'LiveTvController@bulk_delete');

  // director controller

  Route::resource('admin/directors', 'DirectorController');
  Route::post('admin/directors/bulk_delete', 'DirectorController@bulk_delete');
  Route::resource('admin/actors', 'ActorController');
  Route::post('admin/actors/bulk_delete', 'ActorController@bulk_delete');

    // Genres Routes
  Route::resource('admin/genres', 'GenreController');
  Route::post('admin/genres/bulk_delete', 'GenreController@bulk_delete');
  Route::get('admin/update-to-english', 'GenreController@updateAll');

  Route::get('admin/front/slider/limit','SlideUpdateController@get')->name('front.slider.limit');

  Route::post('admin/front/slider/limit/{id}','SlideUpdateController@update')->name('front.slider.update');

  Route::resource('admin/packages', 'PackageController');
  Route::delete('/admin/packages/softdelete/{id}', 'PackageController@softDelete');
  Route::post('admin/packages/bulk_delete', 'PackageController@bulk_delete');
  Route::resource('admin/faqs', 'FaqController');
  Route::post('admin/faqs/bulk_delete', 'FaqController@bulk_delete');
  Route::resource('admin/languages', 'LanguageController');
  Route::post('admin/languages/bulk_delete', 'LanguageController@bulk_delete');
  Route::resource('admin/settings', 'ConfigController');
  Route::get('admin/api-settings', 'ConfigController@setApiView');
  Route::post('admin/api-settings', 'ConfigController@changeEnvKeys');
  /*Mail Setting Routes*/
  Route::get('/admin/mail-setting','ConfigController@getset')->name('mail.getset');
  Route::post('admin/mail-settings', 'ConfigController@changeMailEnvKeys');
  /* end */

  /*Custom style css ad js routes*/
  Route::get('/admin/custom-style-settings', 'CustomStyleController@addStyle')->name('customstyle');
  Route::post('/admin/custom-style-settings/addcss','CustomStyleController@storeCSS')->name('css.store');
  Route::post('/admin/custom-style-settings/addjs','CustomStyleController@storeJS')->name('js.store');
  /*end*/

  /*custom price text routes*/
  Route::get('/admin/pricing-text-set','CustomStyleController@pricingText')->name('pricing.text');
  Route::post('/admin/pricing-text-settings/update','CustomStyleController@pricingTextUpdate')->name('pr.update');
  Route::get('/admin/pricing-text-settings/get/{id}','CustomStyleController@getpricingText')->name('pricing.get');
  /*end*/

  Route::get('/admin/customize/social','SocialIconController@get')->name('social.ico');
  Route::post('/admin/customize/social','SocialIconController@post')->name('socialic');


// notification route
  Route::resource('/admin/notification', 'NotificationController');
  Route::get('/admin/notification/send', 'NotificationController@sendNotification');
  Route::post('admin/notification/bulk_delete', 'NotificationController@bulk_delete');

   // coupon controllers
  Route::resource('admin/coupons', 'CouponController');
  Route::post('admin/coupons/bulk_delete', 'CouponController@bulk_delete');
  Route::resource('admin/audio_language', 'AudioLanguageController');
  Route::post('admin/audio_language/bulk_delete', 'AudioLanguageController@bulk_delete');
  Route::resource('admin/home_slider', 'HomeSliderController');
  Route::post('admin/home_slider/bulk_delete', 'HomeSliderController@bulk_delete');
  Route::post('admin/home_slider/reposition', 'HomeSliderController@slide_reposition')->name('slide_reposition');
  Route::resource('admin/tvseries', 'TvSeriesController');
  Route::post('admin/tvseries/bulk_delete', 'TvSeriesController@bulk_delete');
  Route::get('admin/tvseries/tmdb/translations', 'TvSeriesController@tmdb_translations')->name('tmdb_tv_translate');
  Route::post('admin/tvseries/seasons', 'TvSeriesController@store_seasons');
  Route::patch('admin/tvseries/seasons/{id}', 'TvSeriesController@update_seasons');
  Route::delete('admin/tvseries/seasons/{id}', 'TvSeriesController@destroy_seasons');
  Route::get('admin/tvseries/seasons/{id}/episodes', 'TvSeriesController@show_episodes')->name('show_episodes');
  Route::get('admin/tvseries/seasons/{id}/episodes/{ep_id}', 
    'TvSeriesController@edit_episodes')->name('edit_episodes');
  Route::post('admin/tvseries/seasons/episodes', 'TvSeriesController@store_episodes');
  Route::delete('admin/tvseries/seasons/episodes/{id}', 'TvSeriesController@destroy_episodes');
  Route::patch('admin/tvseries/seasons/episodes/{id}', 'TvSeriesController@update_episodes');
  Route::get('admin/report', 'ReportController@get_report');

  /*page setting routes*/
  Route::get('/admin/page-settings/','CustomStyleController@getPage')->name('pageset');
  
  Route::put('/admin/page-settings/{id}','CustomStyleController@updatePage')->name('pageset.update');

  /*Social Login setting routes*/
  Route::get('/admin/social-login/','SocialLoginController@index')->name('sociallogin');
  Route::put('/admin/social-login/{id}','SocialLoginController@updatePage')->name('sociallogin.update');
  Route::get('admin/social-login/','SocialLoginController@facebook')->name('set.facebook');
  Route::post('admin/facebook','SocialLoginController@updateFacebookKey')->name('key.facebook');
  Route::post('admin/google','SocialLoginController@updateGoogleKey')->name('key.google');
  Route::post('admin/gitlab','SocialLoginController@updategitlabKey')->name('key.gitlab');



  /*end*/
   // adsense routes
  Route::get('/admin/adsensesetting/','AdsenseController@index')->name('adsense');
  Route::put('/admin/adsensesetting/{id}','AdsenseController@update')->name('adsense.update');

    /////////////////////////
    // Customizable Routes //
    /////////////////////////
  Route::resource('admin/customize/landing-page', 'LandingPageController');
  Route::post('admin/customize/landing-page/bulk_delete', 'LandingPageController@bulk_delete');
  Route::post('admin/customize/landing-page/reposition', 'LandingPageController@reposition')->name('landing_page_reposition');
  Route::get('admin/customize/auth-page-customize', 'AuthCustomizeController@index');
  Route::post('admin/customize/auth-page-customize', 'AuthCustomizeController@store');

    // Site Policies Get Method
  Route::get('admin/term&con', function(){
    $config = \App\Config::whereId(1)->first();
    return view('admin.term&con', compact('config'));
  })->name('term_con');
  Route::get('admin/pri_pol', function(){
    $config = \App\Config::whereId(1)->first();
    return view('admin.pri_pol', compact('config'));
  })->name('pri_pol');
  Route::get('admin/refund_pol', function(){
    $config = \App\Config::whereId(1)->first();
    return view('admin.refund_pol', compact('config'));
  })->name('refund_pol');
  Route::get('admin/copyright', function(){
    $config = \App\Config::whereId(1)->first();
    return view('admin.copyright', compact('config'));
  })->name('copyright');

    // Site Policies Patch Method

app/Actor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Actor extends Model
{

    protected $fillable = [
      'name',
      'image',
      'detail',
      'biography',
      'place_of_birth',
      'DOB',
    ];
}

app/Http/Controllers/ActorController.php
<?php

namespace App\Http\Controllers;

use App\Actor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ActorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
     
        
        
         $actors = \DB::table('actors')->select('id','name','image','biography','place_of_birth')->get();

        if($request->ajax()){
             return \Datatables::of($actors)
              ->addIndexColumn()
              ->addColumn('checkbox',function($actor){
                $html = '<div class="inline">
                    <input type="checkbox" form="bulk_delete_form" class="filled-in material-checkbox-input" name="checked[]" value="'.$actor->id.'" id="checkbox'.$actor->id.'">
                    <label for="checkbox'.$actor->id.'" class="material-checkbox"></label>
                  </div>';

                  return $html;
              })
            
               ->addColumn('biography',function($actor){
                    return strip_tags(html_entity_decode(str_limit($actor->biography,50)));
                 
              })
                  ->addColumn('image',function($actor){
                if ($actor->image) {
                 $image= '<img src="'.asset('/images/actors/' . $actor->image).'" alt="Pic" width="70px" class="img-responsive">';
                }else{
                    $image= '<img  src="http://via.placeholder.com/70x70" alt="Pic" width="70px" class="img-responsive">';
                }
               
                   return $image;

              })
              ->addColumn('action',function($actor){
                $btn = ' <div class="admin-table-action-block">
                  
                    <a href="'.route('actors.edit', $actor->id).'" data-toggle="tooltip" data-original-title="Edit" class="btn-info btn-floating"><i class="material-icons">mode_edit</i></a><button type="button" class="btn-danger btn-floating" data-toggle="modal" data-target="#deleteModal'.$actor->id.'"><i class="material-icons">delete</i> </button></div>';
                   
                   

                   $btn.='<div id="deleteModal'.$actor->id.'" class="delete-modal modal fade" role="dialog">
                <div class="modal-dialog modal-sm">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <div class="delete-icon"></div>
                    </div>
                    <div class="modal-body text-center">
                      <h4 class="modal-heading">Are You Sure ?</h4>
                      <p>Do you really want to delete these records? This process cannot be undone.</p>
                    </div>
                    <div class="modal-footer">
                      <form method="POST" action="'.route("actors.destroy",$actor->id).'">
                        '.method_field("DELETE").'
                        '.csrf_field().'
                          <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">No</button>
                          <button type="submit" class="btn btn-danger">Yes</button>
                      </form>
                    </div>
                  </div>
                </div>
              </div>';
                    
                return $btn;
              })
              ->rawColumns(['checkbox','biography','image','action'])
              ->make(true);
        }

    
        return view('admin.actor.index', compact('actors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.actor.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
          'name' => 'required',
          'image' => 'nullable|image|mimes:jpeg,png,jpg'
        ]);

        $input = $request->all();

        if ($file = $request->file('image')) {
          $name = "actor_".time().$file->getClientOriginalName();
          $file->move('images/actors', $name);
          $input['image'] = $name;
        }

        Actor::create($input);
        return back()->with('added', 'Actor has been created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $actor = Actor::findOrFail($id);
        return view('admin.actor.edit', compact('actor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $actor = Actor::findOrFail($id);

        $request->validate([
          'name' => 'required',
          'image' => 'nullable|image|mimes:jpeg,png,jpg'
        ]);
        
        $input = $request->all();

        if ($file = $request->file('image')) {
          $name = "actor_".time().$file->getClientOriginalName();
          if ($actor->image != null) {
              $content = @file_get_contents(public_path().'/images/actors/'.$actor->image);
              if ($content) { 
                unlink(public_path()."/images/actors/".$actor->image);
              }
          }
          $file->move('images/actors', $name);
          $input['image'] = $name;
        }

        $actor->update($input);
        return redirect('admin/actors')->with('updated', 'Actor has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $actor = Actor::findOrFail($id);

        if ($actor->image != null) {
          $content = @file_get_contents(public_path().'/images/actors/'.$actor->image);
          if ($content) { 
            unlink(public_path()."/images/actors/".$actor->image);
          }
        }

        $actor->delete();
        return redirect('admin/actors')->with('deleted', 'Actor has been deleted');
    }

    public function bulk_delete(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'checked' => 'required',
        ]);

        if ($validator->fails()) {

            return back()->with('deleted', 'Please select one of them to delete');
        }

        foreach ($request->checked as $checked) {

            $actor = Actor::findOrFail($checked);
            
            if ($actor->image != null) {
              $content = @file_get_contents(public_path().'/images/actors/'.$actor->image);
              if ($content) { 
                unlink(public_path()."/images/actors/".$actor->image);
              }
            }

            Actor::destroy($checked);
        }

        return back()->with('deleted', 'Actors has been deleted');   
    }
}

resources/views/admin/actor/create.blade.php
@extends('layouts.admin')
@section('title','Create Actor')
@section('content')
  <div class="admin-form-main-block mrg-t-40">
    <h4 class="admin-form-text"><a href="{{url('admin/actors')}}" data-toggle="tooltip" data-original-title="Go back" class="btn-floating"><i class="material-icons">reply</i></a> Create Actor</h4>
    <div class="row">
      <div class="col-md-6">
        <div class="admin-form-block z-depth-1">
          {!! Form::open(['method' => 'POST', 'action' => 'ActorController@store', 'files' => true]) !!}
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                {!! Form::label('name', 'Name') !!}
                <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="Please enter actor name eg:Tom Hardy"></i>
                {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required', 'placeholder' => 'Please enter actor name']) !!}
                <small class="text-danger">{{ $errors->first('name') }}</small>
            </div>
            <div class="form-group{{ $errors->has('biography') ? ' has-error' : '' }}">
                {!! Form::label('biography', 'Biography') !!}
                <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="Please enter actor biography "></i>
                {!! Form::textarea('biography', null, ['class' => 'form-control','row'=>'3', 'placeholder' => 'Please enter actor biography']) !!}
                <small class="text-danger">{{ $errors->first('biography') }}</small>
            </div>
            <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }} input-file-block">
              {!! Form::label('image', 'Actor Image') !!}
              <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="Upload actor image"></i>
              {!! Form::file('image', ['class' => 'input-file', 'id'=>'image']) !!}
              <label for="image" class="btn btn-danger js-labelFile" data-toggle="tooltip" data-original-title="Actor image">
                <i class="icon fa fa-check"></i>
                <span class="js-fileName">Choose a File</span>
              </label>
              <p class="info">Choose custom image</p>
              <small class="text-danger">{{ $errors->first('image') }}</small>
            </div>
            <div class="btn-group pull-right">
              <button type="reset" class="btn btn-info"><i class="material-icons left">toys</i> Reset</button>
              <button type="submit" class="btn btn-success"><i class="material-icons left">add_to_photos</i> Create</button>
            </div>
            <div class="clear-both"></div>
          {!! Form::close() !!}
        </div>  
      </div>
    </div>
  </div>
@endsection

resources/views/admin/actor/edit.blade.php
@extends('layouts.admin')
@section('title',"Edit Actor - $actor->name")
@section('content')
  <div class="admin-form-main-block mrg-t-40">
    <h4 class="admin-form-text"><a href="{{url('admin/actors')}}" data-toggle="tooltip" data-original-title="Go back" class="btn-floating"><i class="material-icons">reply</i></a> Edit Actor</h4>
    <div class="row">
      <div class="col-md-6">
        <div class="admin-form-block z-depth-1">
          {!! Form::model($actor, ['method' => 'PATCH', 'action' => ['ActorController@update', $actor->id], 'files' => true]) !!}
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                {!! Form::label('name', 'Name') !!}
                 <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="Please enter actor name eg:Tom Hardy"></i>
                {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
                <small class="text-danger">{{ $errors->first('name') }}</small>
            </div>
               <div class="form-group{{ $errors->has('biography') ? ' has-error' : '' }}">
                {!! Form::label('biography', 'Biography') !!}
                <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="Please enter actor biography "></i>
                {!! Form::textarea('biography', null, ['class' => 'form-control','row'=>'3', 'placeholder' => 'Please enter actor biography']) !!}
                <small class="text-danger">{{ $errors->first('biography') }}</small>
            </div>
            <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }} input-file-block">
              {!! Form::label('image', 'Actor Image') !!}
               <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="Upload actor image"></i>
              {!! Form::file('image', ['class' => 'input-file', 'id'=>'image']) !!}
              <label for="image" class="btn btn-danger js-labelFile" data-toggle="tooltip" data-original-title="Actor image">
                <i class="icon fa fa-check"></i>
                <span class="js-fileName">Choose a File</span>
              </label>
              <p class="info">Choose custom image</p>
              <small class="text-danger">{{ $errors->first('image') }}</small>
            </div>
            <div class="btn-group pull-right">
              <button type="submit" class="btn btn-success"><i class="material-icons left">add_to_photos</i> Update</button>
            </div>
            <div class="clear-both"></div>
          {!! Form::close() !!}
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/admin/actor/index.blade.php
@extends('layouts.admin')
@section('title','All Actors')
@section('content')
<div class="content-main-block mrg-t-40">
  <div class="admin-create-btn-block">
    <a href="{{route('actors.create')}}" class="btn btn-danger btn-md"><i class="material-icons left">add</i> Create Actor</a>
    <!-- Delete Modal -->
    <a type="button" class="btn btn-danger btn-md" data-toggle="modal" data-target="#bulk_delete"><i class="material-icons left">delete</i> Delete Selected</a>   
    <!-- Modal -->
    <div id="bulk_delete" class="delete-modal modal fade" role="dialog">
      <div class="modal-dialog modal-sm">
        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <div class="delete-icon"></div>
          </div>
          <div class="modal-body text-center">
            <h4 class="modal-heading">Are You Sure ?</h4>
            <p>Do you really want to delete these records? This process cannot be undone.</p>
          </div>
          <div class="modal-footer">
            {!! Form::open(['method' => 'POST', 'action' => 'ActorController@bulk_delete', 'id' => 'bulk_delete_form']) !!}
            <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">No</button>
            <button type="submit" class="btn btn-danger">Yes</button>
            {!! Form::close() !!}
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="content-block box-body table-responsive">
    <table id="actorTable" class="table table-hover">
      <thead>
        <tr class="table-heading-row">
          <th>
            <div class="inline">
              <input id="checkboxAll" type="checkbox" class="filled-in" name="checked[]" value="all" id="checkboxAll">
              <label for="checkboxAll" class="material-checkbox"></label>
            </div>
            #
          </th>
            <th>Image</th>
            <th>Name</th>
            <th>Biography</th>
            <th>Birth Place</th>
      
            <th>Actions</th>
        </tr>
      </thead>
      @if ($actors)
      <tbody>
       
      </tbody>
      @endif
    </table>
  </div>
</div>
@endsection
@section('custom-script')
<script>
  $(function(){
    $('#checkboxAll').on('change', function(){
      if($(this).prop("checked") == true){
        $('.material-checkbox-input').attr('checked', true);
      }
      else if($(this).prop("checked") == false){
        $('.material-checkbox-input').attr('checked', false);
      }
    });
  });
</script>
<script>
  $(function () {

    var table = $('#actorTable').DataTable({
      processing: true,
      serverSide: true,
      responsive: true,
      autoWidth: false,
      scrollCollapse: true,


      ajax: "{{ route('actors.index') }}",
      columns: [

      {data: 'checkbox', name: 'checkbox',orderable: false, searchable: false},
      {data: 'image', name: 'image'},
      {data: 'name', name: 'name'},
      {data: 'biography', name: 'biography'},
      {data: 'place_of_birth', name: 'place_of_birth'},

      {data: 'action', name: 'action',searchable: false}

      ],
      dom : 'lBfrtip',
      buttons : [
      'csv','excel','pdf','print'
      ],
      order : [[0,'desc']]
    });

  });
</script>
@endsection