routes/web.php
// Language switch middleware 
Route::get('language-switch/{local}', 'LanguageSwitchController@languageSwitch')->name('languageSwitch');

// Routes With Web, Auth Middlewares
Route::group(['middleware' => ['web', 'auth' ,'switch_languages']], function () {
    // User Account routes without subscription
  Route::get('account', 'UserAccountController@index');
 
  Route::get('contactus','ContactController@contact')->name('contactus');
  Route::post('send/contactus','ContactController@send')->name('send.contactus');
  Route::get('account/profile', 'UserAccountController@edit_profile');
  Route::post('account/profile', 'UserAccountController@update_profile');
  Route::post('account/profile/age','UsersController@update_age');
  Route::get('account/purchaseplan', 'UserAccountController@purchase_plan');
  Route::get('account/purchase/{id}', 'UserAccountController@get_payment')->name('get_payment');
  Route::post('account/purchase', 'UserAccountController@subscribe');
  Route::get('account/billing_history', 'UserAccountController@history');
  Route::post('emailsubscribe', 'emailSubscribe@subscribe');
  Route::post('paypal_subscription', 'PaypalController@postPaymentWithpaypal')->name('paypal_subscription');
  Route::get('paypal_subscription', 'PaypalController@getPaymentStatus')->name('getPaymentStatus');
  Route::get('paypal_subscription_failed', 'PaypalController@getPaymentFailed')->name('getPaymentFailed');
  // rating routes
  Route::POST('video/rating', 'UserRatingController@store');
  Route::POST('video/rating/tv', 'UserRatingController@tvstore');
  // susbscription routes
  Route::get('payment/braintree', 'BrainTreeController@get_bt');
  Route::post('payment/braintree', 'BrainTreeController@payment');
  Route::get('payment/coinpayment', 'CoinpaymentsController@get_bt');
  Route::post('payment/coinpayment', 'CoinpaymentsController@purchaseItems');
  Route::post('payment/paystack', 'PaystackController@paystackgateway');
  Route::get('paystack/callback', 'PaystackController@paystackcallback'); 
    // Paypal Routes
  Route::get('paypal/cancel-subscription', 'UserAccountController@PaypalCancel')->name('cancelSubPaypal');
  Route::get('paypal/resume-subscription', 'UserAccountController@PaypalResume')->name('resumeSubPaypal');

    # Status Route
  Route::get('payment/status', 'PayuController@status');
  Route::post('payment/payu', 'PayuController@payment');

   Route::post('/payviarazorpaysuccess/{planid}','PayViaRazorpayController@success')->name('paysuccess');
});

// Routes With Web, Auth, Administrator Middlewares
Route::group(['middleware' => ['web', 'auth', 'is_admin', 'switch_languages']], function () {

  Route::get('/viewstracker',function(){
   $movies =  Movie::orderByUniqueViews()->get();
   $season =  Season::orderByUniqueViews()->get();
   return view('admin.viewtracker',compact('movies','season'));
 })->name('view.track');

  Route::get('/quick/change/status/{id}','QuickUpdateController@change')->name('quick.movie.status');

  Route::get('/quick/change/status/tvseries/{id}','QuickUpdateController@changetvstatus')->name('quick.tv.status');

  Route::get('/admin/pending/movie','MovieController@addedMovies')->name('addedmovies');

  Route::get('/admin/pending/tvshows','TvSeriesController@addedTvSeries')->name('addedTvSeries');

  Route::get('/admin/pending/livtvs','LiveTvController@addedLiveTv')->name('addedLiveTv');

  Route::resource('admin/blog', 'BlogController');
  
  Route::post('admin/blog/bulk_delete', 'BlogController@bulk_delete');
  
  Route::post('admin/blog/create', 'BlogController@create');
  
  Route::patch('admin/blog/update/{id}', 'BlogController@update');
  
  Route::delete('admin/blog/destroy/{id}', 'BlogController@destroy');

  Route::post('admin/movie/{id}/addsubtitle','SubtitleController@post')->name('add.subtitle');

  Route::post('admin/movie/{id}/delete/subtitle','SubtitleController@delete')->name('del.subtitle');

  Route::get('admin', 'DashboardController@dashboard')->name('dashboard');

  Route::get('admin/profile', function(){
    $auth = Auth::user();
    return view('admin.profile', compact('auth'));
  });

  Route::get('/admin/player-setting','PlayerSettingController@get')->name('player.set');
  Route::post('/admin/player-setting/update','PlayerSettingController@update')->name('player.update');

  Route::resource('admin/menu', 'MenuController');
  Route::post('admin/menu/bulk_delete', 'MenuController@bulk_delete');
  Route::post('admin/menu/reposition', 'MenuController@reposition')->name('menu_reposition');

  Route::resource('admin/users', 'UsersController');
  Route::get('admin/user/status/{id}','UsersController@changestatus');

  Route::get('user/subscription/{id}', 'UsersController@change_subscription_show')->name('change_subscription_show');
  Route::post('user/subscription', 'UsersController@change_subscription')->name('change_subscription');
  Route::post('admin/users/bulk_delete', 'UsersController@bulk_delete');
  Route::resource('admin/movies', 'MovieController');
  Route::get('admin/movie/upload_video/converting', 'MovieController@upload_video');
   Route::get('admin/tvshow/upload_video/converting', 'TvSeriesController@upload_video');
  Route::get('admin/movie/vimeoapi', 'MovieController@vimeoApicall');
  
  Route::get('admin/movies/tmdb/translations', 'MovieController@tmdb_translations')->name('tmdb_movie_translate');
  Route::post('admin/movies/bulk_delete', 'MovieController@bulk_delete');

  // live tv routes
  Route::resource('admin/livetv', 'LiveTvController');
  Route::get('admin/livetv/upload_video/converting', 'LiveTvController@upload_video');
  Route::get('admin/livetv/vimeoapi', 'LiveTvController@vimeoApicall');
  
  Route::get('admin/livetv/tmdb/translations', 'LiveTvController@tmdb_translations')->name('tmdb_movie_translate');
  Route::post('admin/livetv/bulk_delete', 'LiveTvController@bulk_delete');

  // director controller

  Route::resource('admin/directors', 'DirectorController');
  Route::post('admin/directors/bulk_delete', 'DirectorController@bulk_delete');
  Route::resource('admin/actors', 'ActorController');
  Route::post('admin/actors/bulk_delete', 'ActorController@bulk_delete');

    // Genres Routes
  Route::resource('admin/genres', 'GenreController');
  Route::post('admin/genres/bulk_delete', 'GenreController@bulk_delete');
  Route::get('admin/update-to-english', 'GenreController@updateAll');

  Route::get('admin/front/slider/limit','SlideUpdateController@get')->name('front.slider.limit');

  Route::post('admin/front/slider/limit/{id}','SlideUpdateController@update')->name('front.slider.update');

  Route::resource('admin/packages', 'PackageController');
  Route::delete('/admin/packages/softdelete/{id}', 'PackageController@softDelete');
  Route::post('admin/packages/bulk_delete', 'PackageController@bulk_delete');
  Route::resource('admin/faqs', 'FaqController');
  Route::post('admin/faqs/bulk_delete', 'FaqController@bulk_delete');
  Route::resource('admin/languages', 'LanguageController');
  Route::post('admin/languages/bulk_delete', 'LanguageController@bulk_delete');
  Route::resource('admin/settings', 'ConfigController');
  Route::get('admin/api-settings', 'ConfigController@setApiView');
  Route::post('admin/api-settings', 'ConfigController@changeEnvKeys');
  /*Mail Setting Routes*/
  Route::get('/admin/mail-setting','ConfigController@getset')->name('mail.getset');
  Route::post('admin/mail-settings', 'ConfigController@changeMailEnvKeys');
  /* end */

  /*Custom style css ad js routes*/
  Route::get('/admin/custom-style-settings', 'CustomStyleController@addStyle')->name('customstyle');
  Route::post('/admin/custom-style-settings/addcss','CustomStyleController@storeCSS')->name('css.store');
  Route::post('/admin/custom-style-settings/addjs','CustomStyleController@storeJS')->name('js.store');
  /*end*/

  /*custom price text routes*/
  Route::get('/admin/pricing-text-set','CustomStyleController@pricingText')->name('pricing.text');
  Route::post('/admin/pricing-text-settings/update','CustomStyleController@pricingTextUpdate')->name('pr.update');
  Route::get('/admin/pricing-text-settings/get/{id}','CustomStyleController@getpricingText')->name('pricing.get');
  /*end*/

  Route::get('/admin/customize/social','SocialIconController@get')->name('social.ico');
  Route::post('/admin/customize/social','SocialIconController@post')->name('socialic');


// notification route
  Route::resource('/admin/notification', 'NotificationController');
  Route::get('/admin/notification/send', 'NotificationController@sendNotification');
  Route::post('admin/notification/bulk_delete', 'NotificationController@bulk_delete');

   // coupon controllers
  Route::resource('admin/coupons', 'CouponController');
  Route::post('admin/coupons/bulk_delete', 'CouponController@bulk_delete');
  Route::resource('admin/audio_language', 'AudioLanguageController');
  Route::post('admin/audio_language/bulk_delete', 'AudioLanguageController@bulk_delete');
  Route::resource('admin/home_slider', 'HomeSliderController');
  Route::post('admin/home_slider/bulk_delete', 'HomeSliderController@bulk_delete');
  Route::post('admin/home_slider/reposition', 'HomeSliderController@slide_reposition')->name('slide_reposition');
  Route::resource('admin/tvseries', 'TvSeriesController');
  Route::post('admin/tvseries/bulk_delete', 'TvSeriesController@bulk_delete');
  Route::get('admin/tvseries/tmdb/translations', 'TvSeriesController@tmdb_translations')->name('tmdb_tv_translate');
  Route::post('admin/tvseries/seasons', 'TvSeriesController@store_seasons');
  Route::patch('admin/tvseries/seasons/{id}', 'TvSeriesController@update_seasons');
  Route::delete('admin/tvseries/seasons/{id}', 'TvSeriesController@destroy_seasons');
  Route::get('admin/tvseries/seasons/{id}/episodes', 'TvSeriesController@show_episodes')->name('show_episodes');
  Route::get('admin/tvseries/seasons/{id}/episodes/{ep_id}', 
    'TvSeriesController@edit_episodes')->name('edit_episodes');

resources/views/admin/livetv/addedindex.blade.php
@extends('layouts.admin')
@section('title','All Live Tv')
@section('content')
  <div class="content-main-block mrg-t-40">
    <div class="admin-create-btn-block">
      <a href="{{route('livetv.create')}}" class="btn btn-danger btn-md"><i class="material-icons left">add</i> Create LIVETV</a>
      <!-- Delete Modal -->
      <a type="button" class="btn btn-danger btn-md" data-toggle="modal" data-target="#bulk_delete"><i class="material-icons left">delete</i> Delete Selected</a>   
      @if (Session::has('changed_language'))
        <a href="{{ route('tmdb_movie_translate') }}" class="btn btn-danger btn-md"><i class="material-icons left">translate</i> Translate all to {{Session::get('changed_language')}}</a>   
      @endif
      <!-- Modal -->
      <div id="bulk_delete" class="delete-modal modal fade" role="dialog">
        <div class="modal-dialog modal-sm">
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <div class="delete-icon"></div>
            </div>
            <div class="modal-body text-center">
              <h4 class="modal-heading">Are You Sure ?</h4>
              <p>Do you really want to delete these records? This process cannot be undone.</p>
            </div>
            <div class="modal-footer">
              {!! Form::open(['method' => 'POST', 'action' => 'MovieController@bulk_delete', 'id' => 'bulk_delete_form']) !!}
                <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">No</button>
                <button type="submit" class="btn btn-danger">Yes</button>
              {!! Form::close() !!}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="content-block box-body">
      <table id="moviesTable" class="table table-hover">
        <thead>
          <tr class="table-heading-row">
            <th>
              <div class="inline">
                <input id="checkboxAll" type="checkbox" class="filled-in" name="checked[]" value="all" id="checkboxAll">
                <label for="checkboxAll" class="material-checkbox"></label>
              </div>
              #
            </th>
            <th>Thumbnail</th>
            <th>Live Title</th>
            <th>Featured</th>
            <th>Status</th>
            <th>Created By</th>
            <th>Actions</th>
          </tr>
        </thead>
          @if ($movies)
          <tbody>
           
          </tbody>
        @endif  
      
      </table>
    </div>
  </div>
@endsection
@section('custom-script')
  <script>
    $(function(){
      $('#checkboxAll').on('change', function(){
        if($(this).prop("checked") == true){
          $('.material-checkbox-input').attr('checked', true);
        }
        else if($(this).prop("checked") == false){
          $('.material-checkbox-input').attr('checked', false);
        }
      });
    });
  </script>
   
<script>
     $(document).ready(function() {
  var SITEURL = '{{URL::to('')}}';

 
        $.ajax({
            type: "GET",
            url: SITEURL + "/admin/livetv/upload_video/converting",
            success: function (data) {
           console.log('Success:',data);
            },
            error: function (data) {
                console.log('Error:', data);
            }
        });

    
     });
</script>
  <script>
 
    $(function () {
      
      var table = $('#moviesTable').DataTable({
          processing: true,
          serverSide: true,
         responsive: true,
         autoWidth: false,
         scrollCollapse: true,
       
         
          ajax: "{{ route('addedLiveTv') }}",
          columns: [
              
              {data: 'checkbox', name: 'checkbox',orderable: false, searchable: false},
            
              {data: 'thumbnail', name: 'thumbnail'},
              {data: 'title', name: 'title'},
           
              {data: 'featured', name: 'featured',searchable: false},
              {data: 'addedby', name: 'addedby',searchable: false},
              {data: 'status', name: 'status',searchable: false},
              {data: 'action', name: 'action',searchable: false}
             
          ],
          dom : 'lBfrtip',
          buttons : [
            'csv','excel','pdf','print'
          ],
          order : [[0,'desc']]
      });
      
    });
  </script>


  <script>
    $(function(){
      $('#checkboxAll').on('change', function(){
        if($(this).prop("checked") == true){
          $('.material-checkbox-input').attr('checked', true);
        }
        else if($(this).prop("checked") == false){
          $('.material-checkbox-input').attr('checked', false);
        }
      });
    });
  </script>
@endsection

resources/views/admin/livetv/index.blade.php
@extends('layouts.admin')
@section('title','All Live Tv')
@section('content')
  <div class="content-main-block mrg-t-40">
    <div class="admin-create-btn-block">
      <a href="{{route('livetv.create')}}" class="btn btn-danger btn-md"><i class="material-icons left">add</i> Create LIVETV</a>
      <!-- Delete Modal -->
      <a type="button" class="btn btn-danger btn-md" data-toggle="modal" data-target="#bulk_delete"><i class="material-icons left">delete</i> Delete Selected</a>   
      @if (Session::has('changed_language'))
        <a href="{{ route('tmdb_movie_translate') }}" class="btn btn-danger btn-md"><i class="material-icons left">translate</i> Translate all to {{Session::get('changed_language')}}</a>   
      @endif
      <!-- Modal -->
      <div id="bulk_delete" class="delete-modal modal fade" role="dialog">
        <div class="modal-dialog modal-sm">
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <div class="delete-icon"></div>
            </div>
            <div class="modal-body text-center">
              <h4 class="modal-heading">Are You Sure ?</h4>
              <p>Do you really want to delete these records? This process cannot be undone.</p>
            </div>
            <div class="modal-footer">
              {!! Form::open(['method' => 'POST', 'action' => 'MovieController@bulk_delete', 'id' => 'bulk_delete_form']) !!}
                <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">No</button>
                <button type="submit" class="btn btn-danger">Yes</button>
              {!! Form::close() !!}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="content-block box-body">
      <table id="moviesTable" class="table table-hover">
        <thead>
          <tr class="table-heading-row">
            <th>
              <div class="inline">
                <input id="checkboxAll" type="checkbox" class="filled-in" name="checked[]" value="all" id="checkboxAll">
                <label for="checkboxAll" class="material-checkbox"></label>
              </div>
              #
            </th>
            <th>Thumbnail</th>
            <th>Live Title</th>
            <th>Featured</th>
            <th>Status</th>
            <th>Created By</th>
            <th>Actions</th>
          </tr>
        </thead>
          @if ($movies)
          <tbody>
           
          </tbody>
        @endif  
      
      </table>
    </div>
  </div>
@endsection
@section('custom-script')
  <script>
    $(function(){
      $('#checkboxAll').on('change', function(){
        if($(this).prop("checked") == true){
          $('.material-checkbox-input').attr('checked', true);
        }
        else if($(this).prop("checked") == false){
          $('.material-checkbox-input').attr('checked', false);
        }
      });
    });
  </script>
   
<script>
     $(document).ready(function() {
  var SITEURL = '{{URL::to('')}}';

 
        $.ajax({
            type: "GET",
            url: SITEURL + "/admin/livetv/upload_video/converting",
            success: function (data) {
           console.log('Success:',data);
            },
            error: function (data) {
                console.log('Error:', data);
            }
        });

    
     });
</script>
  <script>
 
    $(function () {
      
      var table = $('#moviesTable').DataTable({
          processing: true,
          serverSide: true,
         responsive: true,
         autoWidth: false,
         scrollCollapse: true,
       
         
          ajax: "{{ route('livetv.index') }}",
          columns: [
              
              {data: 'checkbox', name: 'checkbox',orderable: false, searchable: false},
            
              {data: 'thumbnail', name: 'thumbnail'},
              {data: 'title', name: 'title'},
           
              {data: 'featured', name: 'featured',searchable: false},
              {data: 'addedby', name: 'addedby',searchable: false},
              {data: 'status', name: 'status',searchable: false},
              {data: 'action', name: 'action',searchable: false}
             
          ],
          dom : 'lBfrtip',
          buttons : [
            'csv','excel','pdf','print'
          ],
          order : [[0,'desc']]
      });
      
    });
  </script>


  <script>
    $(function(){
      $('#checkboxAll').on('change', function(){
        if($(this).prop("checked") == true){
          $('.material-checkbox-input').attr('checked', true);
        }
        else if($(this).prop("checked") == false){
          $('.material-checkbox-input').attr('checked', false);
        }
      });
    });
  </script>
@endsection