routes/web.php
  Route::get('admin/livetv/vimeoapi', 'LiveTvController@vimeoApicall');
  
  Route::get('admin/livetv/tmdb/translations', 'LiveTvController@tmdb_translations')->name('tmdb_movie_translate');
  Route::post('admin/livetv/bulk_delete', 'LiveTvController@bulk_delete');

  // director controller

  Route::resource('admin/directors', 'DirectorController');
  Route::post('admin/directors/bulk_delete', 'DirectorController@bulk_delete');
  Route::resource('admin/actors', 'ActorController');
  Route::post('admin/actors/bulk_delete', 'ActorController@bulk_delete');

    // Genres Routes
  Route::resource('admin/genres', 'GenreController');
  Route::post('admin/genres/bulk_delete', 'GenreController@bulk_delete');
  Route::get('admin/update-to-english', 'GenreController@updateAll');

  Route::get('admin/front/slider/limit','SlideUpdateController@get')->name('front.slider.limit');

  Route::post('admin/front/slider/limit/{id}','SlideUpdateController@update')->name('front.slider.update');

  Route::resource('admin/packages', 'PackageController');
  Route::delete('/admin/packages/softdelete/{id}', 'PackageController@softDelete');
  Route::post('admin/packages/bulk_delete', 'PackageController@bulk_delete');
  Route::resource('admin/faqs', 'FaqController');
  Route::post('admin/faqs/bulk_delete', 'FaqController@bulk_delete');
  Route::resource('admin/languages', 'LanguageController');
  Route::post('admin/languages/bulk_delete', 'LanguageController@bulk_delete');
  Route::resource('admin/settings', 'ConfigController');
  Route::get('admin/api-settings', 'ConfigController@setApiView');
  Route::post('admin/api-settings', 'ConfigController@changeEnvKeys');
  /*Mail Setting Routes*/
  Route::get('/admin/mail-setting','ConfigController@getset')->name('mail.getset');
  Route::post('admin/mail-settings', 'ConfigController@changeMailEnvKeys');
  /* end */

  /*Custom style css ad js routes*/
  Route::get('/admin/custom-style-settings', 'CustomStyleController@addStyle')->name('customstyle');
  Route::post('/admin/custom-style-settings/addcss','CustomStyleController@storeCSS')->name('css.store');
  Route::post('/admin/custom-style-settings/addjs','CustomStyleController@storeJS')->name('js.store');
  /*end*/

  /*custom price text routes*/
  Route::get('/admin/pricing-text-set','CustomStyleController@pricingText')->name('pricing.text');
  Route::post('/admin/pricing-text-settings/update','CustomStyleController@pricingTextUpdate')->name('pr.update');
  Route::get('/admin/pricing-text-settings/get/{id}','CustomStyleController@getpricingText')->name('pricing.get');
  /*end*/

  Route::get('/admin/customize/social','SocialIconController@get')->name('social.ico');
  Route::post('/admin/customize/social','SocialIconController@post')->name('socialic');


// notification route
  Route::resource('/admin/notification', 'NotificationController');
  Route::get('/admin/notification/send', 'NotificationController@sendNotification');
  Route::post('admin/notification/bulk_delete', 'NotificationController@bulk_delete');

   // coupon controllers
  Route::resource('admin/coupons', 'CouponController');
  Route::post('admin/coupons/bulk_delete', 'CouponController@bulk_delete');
  Route::resource('admin/audio_language', 'AudioLanguageController');
  Route::post('admin/audio_language/bulk_delete', 'AudioLanguageController@bulk_delete');
  Route::resource('admin/home_slider', 'HomeSliderController');
  Route::post('admin/home_slider/bulk_delete', 'HomeSliderController@bulk_delete');
  Route::post('admin/home_slider/reposition', 'HomeSliderController@slide_reposition')->name('slide_reposition');
  Route::resource('admin/tvseries', 'TvSeriesController');
  Route::post('admin/tvseries/bulk_delete', 'TvSeriesController@bulk_delete');
  Route::get('admin/tvseries/tmdb/translations', 'TvSeriesController@tmdb_translations')->name('tmdb_tv_translate');
  Route::post('admin/tvseries/seasons', 'TvSeriesController@store_seasons');
  Route::patch('admin/tvseries/seasons/{id}', 'TvSeriesController@update_seasons');
  Route::delete('admin/tvseries/seasons/{id}', 'TvSeriesController@destroy_seasons');
  Route::get('admin/tvseries/seasons/{id}/episodes', 'TvSeriesController@show_episodes')->name('show_episodes');
  Route::get('admin/tvseries/seasons/{id}/episodes/{ep_id}', 
    'TvSeriesController@edit_episodes')->name('edit_episodes');
  Route::post('admin/tvseries/seasons/episodes', 'TvSeriesController@store_episodes');
  Route::delete('admin/tvseries/seasons/episodes/{id}', 'TvSeriesController@destroy_episodes');
  Route::patch('admin/tvseries/seasons/episodes/{id}', 'TvSeriesController@update_episodes');
  Route::get('admin/report', 'ReportController@get_report');

  /*page setting routes*/
  Route::get('/admin/page-settings/','CustomStyleController@getPage')->name('pageset');
  
  Route::put('/admin/page-settings/{id}','CustomStyleController@updatePage')->name('pageset.update');

  /*Social Login setting routes*/
  Route::get('/admin/social-login/','SocialLoginController@index')->name('sociallogin');
  Route::put('/admin/social-login/{id}','SocialLoginController@updatePage')->name('sociallogin.update');
  Route::get('admin/social-login/','SocialLoginController@facebook')->name('set.facebook');
  Route::post('admin/facebook','SocialLoginController@updateFacebookKey')->name('key.facebook');
  Route::post('admin/google','SocialLoginController@updateGoogleKey')->name('key.google');
  Route::post('admin/gitlab','SocialLoginController@updategitlabKey')->name('key.gitlab');



  /*end*/
   // adsense routes
  Route::get('/admin/adsensesetting/','AdsenseController@index')->name('adsense');
  Route::put('/admin/adsensesetting/{id}','AdsenseController@update')->name('adsense.update');

    /////////////////////////
    // Customizable Routes //
    /////////////////////////
  Route::resource('admin/customize/landing-page', 'LandingPageController');
  Route::post('admin/customize/landing-page/bulk_delete', 'LandingPageController@bulk_delete');
  Route::post('admin/customize/landing-page/reposition', 'LandingPageController@reposition')->name('landing_page_reposition');
  Route::get('admin/customize/auth-page-customize', 'AuthCustomizeController@index');
  Route::post('admin/customize/auth-page-customize', 'AuthCustomizeController@store');

    // Site Policies Get Method
  Route::get('admin/term&con', function(){
    $config = \App\Config::whereId(1)->first();
    return view('admin.term&con', compact('config'));
  })->name('term_con');
  Route::get('admin/pri_pol', function(){
    $config = \App\Config::whereId(1)->first();
    return view('admin.pri_pol', compact('config'));
  })->name('pri_pol');
  Route::get('admin/refund_pol', function(){
    $config = \App\Config::whereId(1)->first();
    return view('admin.refund_pol', compact('config'));
  })->name('refund_pol');
  Route::get('admin/copyright', function(){
    $config = \App\Config::whereId(1)->first();
    return view('admin.copyright', compact('config'));
  })->name('copyright');

    // Site Policies Patch Method
  Route::patch('admin/term&con', function(\Illuminate\Http\Request $request){
    $config = \App\Config::whereId(1)->first();
    $input = $request->all();
    $config->update($input);
    return back()->with('updated', 'Terms & Condition has been updated');
  })->name('term&con');
  Route::patch('admin/pri_pol', function(\Illuminate\Http\Request $request){
    $config = \App\Config::whereId(1)->first();
    $input = $request->all();
    $config->update($input);
    return back()->with('updated', 'Privacy Policy has been updated');
  })->name('pri_pol');
  Route::patch('admin/refund_pol', function(\Illuminate\Http\Request $request){
    $config = \App\Config::whereId(1)->first();
    $input = $request->all();
    $config->update($input);
    return back()->with('updated', 'Refund Policy has been updated');
  })->name('refund_pol');
  Route::patch('admin/copyright', function(\Illuminate\Http\Request $request){
    $config = \App\Config::whereId(1)->first();
    $input = $request->all();
    $config->update($input);
    return back()->with('updated', 'Copyright text has been updated');
  })->name('copyright');

    /////////////////////////////////
    // Language Translation Routes //
    /////////////////////////////////
    // Header Translation Routes
  Route::get('admin/header-translations', 'HeaderTranslationController@index')->name('header-translation-index');
  Route::post('admin/header-translations', 'HeaderTranslationController@update');

    // Footer Translation Routes
  Route::get('admin/footer-translations', 'FooterTranslationController@index')->name('footer-translation-index');
  Route::post('admin/footer-translations', 'FooterTranslationController@update');

    // Home Page Translation Routes
  Route::get('admin/home-translations', 'HomeTranslationController@index')->name('home-translation-index');
  Route::post('admin/home-translations', 'HomeTranslationController@update');

    // Popover Detail Translation Routes
  Route::get('admin/popover-detail-translations', 'PopoverTranslationController@index')->name('popover-detail-translation-index');
  Route::post('admin/popover-detail-translations', 'PopoverTranslationController@update');

});

Route::group(['middleware' => ['web', 'auth', 'is_subscriber', 'switch_languages']], function () {

  Route::get('/changescreen/{id}','MultipleScreenController@newupdate');

  Route::get('/manageprofile/mus/{id}','MultipleScreenController@manageprofile')->name('manageprofile');

  Route::post('/manageprofile/mus/{id}','MultipleScreenController@updateprofile')->name('mus.pro.update');

});

// Routes With Web, Auth And Subscriber Middlewares
Route::group(['middleware' => ['web', 'auth', 'is_subscriber','login_limit', 'switch_languages']], function () {

  Route::post('/update/screen/{id}','MultipleScreenController@update')->name('mus.update');
  
  Route::get('/viewall/{menuid}/{menuname}','HomeController@showall')->name('showall');

app/Http/Controllers/HomeSliderController.php
<?php

namespace App\Http\Controllers;

use App\HomeSlider;
use App\Movie;
use App\TvSeries;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class HomeSliderController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $home_slides = HomeSlider::orderBy('position', 'asc')->get();
        return view('admin.homeslider.index', compact('home_slides'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $movie_list = Movie::pluck('title', 'id')->all();
        $tv_series_list = TvSeries::pluck('title', 'id')->all();
        return view('admin.homeslider.create', compact('movie_list', 'tv_series_list'));
    }

    /**
     * Store a newly created resource in storage.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
           'slide_image' => 'required|image|mimes:png,jpeg,jpg,gif'
        ]);

        $input = $request->all();

        if ($file = $request->file('slide_image'))
        {
          $name = 'slide_' . time() . $file->getClientOriginalName();
          if ($request->movie_id != null && $request->movie_id != '')
          {
            $file->move('images/home_slider/movies/', $name);
          } elseif ($request->tv_series_id != null && $request->tv_series_id != '') {
            $file->move('images/home_slider/shows/', $name);
          }
          $input['slide_image'] = $name;
        }

        if (!isset($input['active']))
        {
          $input['active'] = 0;
        }

        $input['position'] = (HomeSlider::count()+1);

        HomeSlider::create($input);

        return back()->with('added', 'Slide has been added');

    }

    /**
     * Display the specified resource.
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $home_slide = HomeSlider::findOrFail($id);
        if ($home_slide->movie_id != null) {
            $movie_dtl = Movie::findOrFail($home_slide->movie_id);
            $movie_list = Movie::pluck('title', 'id')->all();
            $tv_series_list = TvSeries::pluck('title', 'id')->all();
            return view('admin.homeslider.edit', compact('home_slide', 'movie_list', 'tv_series_list', 'movie_dtl'));
        } elseif ($home_slide->tv_series_id != null) {
            $tv_series_dtl = TvSeries::findOrFail($home_slide->tv_series_id);
            $movie_list = Movie::pluck('title', 'id')->all();
            $tv_series_list = TvSeries::pluck('title', 'id')->all();
            return view('admin.homeslider.edit', compact('home_slide', 'movie_list', 'tv_series_list', 'tv_series_dtl'));
        }

    }

    /**
     * Update the specified resource in storage.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'slide_image' => 'nullable|image|mimes:png,jpeg,jpg,gif'
        ]);

        $input = $request->all();

        $slide = HomeSlider::findOrFail($id);

        if ($file = $request->file('slide_image'))
        {
          $name = 'slide_' . time() . $file->getClientOriginalName();
          if ($request->movie_id != null && $request->movie_id != '')
          {
            if ($slide->slide_image != null) {
              $image_file = @file_get_contents(public_path().'/images/home_slider/'. $slide->slide_image);
              if($image_file){
                unlink(public_path(). '/images/home_slider/movies' . $slide->slide_image);
              }
            }
            $file->move('images/home_slider/movies', $name);
          } elseif ($request->tv_series_id != null && $request->tv_series_id != '') {
            if ($slide->slide_image != null) {
              $image_file = @file_get_contents(public_path().'/images/home_slider/'. $slide->slide_image);
              if($image_file){
                unlink(public_path(). '/images/home_slider/shows' . $slide->slide_image);
              }
            }
            $file->move('images/home_slider/shows', $name);
          }
          $input['slide_image'] = $name;
        }

        if (!isset($input['active']))
        {
          $input['active'] = 0;
        }

        $slide->update($input);
        return redirect('admin/home_slider')->with('updated', 'Slide has been updated');
    }

    /**
     * Remove the specified resource from storage.
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $home_slide = HomeSlider::findOrFail($id);

        if ($home_slide->slide_image != null) {
          if ($home_slide->movie_id != null) {
            $content = @file_get_contents(public_path() . '/images/home_slider/movies/'.$home_slide->slide_image);
            if ($content) {
              unlink(public_path() . '/images/home_slider/movies/'.$home_slide->slide_image);
            }
          }
          elseif($home_slide->tv_series_id != null) {
            $content = @file_get_contents(public_path() . '/images/home_slider/shows/'.$home_slide->slide_image);
            if ($content) {
              unlink(public_path() . '/images/home_slider/shows/'.$home_slide->slide_image);
            }
          }
        }
        $home_slide->delete();
        return back()->with('deleted', 'Slide has been deleted');
    }


    public function slide_reposition(Request $request)
    {
      if($request->item != null)
      {
          $items = explode('&', $request->item);
          $all_ids = collect();
          foreach ($items as $key => $value) {
              $all_ids->push(substr($value, 7));
          }

          $i = 0;

          foreach($all_ids as $id)
          {
              $i++;
              $item = HomeSlider::findOrFail($id);
              $item->position = $i;
              $item->save();
          }

          return response()->json(['success' => true]);

      }

      else
      {
          return response()->json(['success' => false]);
      }
    }

    public function bulk_delete(Request $request)
    {
      $validator = Validator::make($request->all(), [
          'checked' => 'required',
      ]);

      if ($validator->fails()) {
          return back()->with('deleted', 'Please select one of them to delete');
      }

      foreach ($request->checked as $checked) {
        $home_slide = HomeSlider::findOrFail($checked);

        if ($home_slide->slide_image != null) {
          if ($home_slide->movie_id != null) {
            $content = @file_get_contents(public_path() . '/images/home_slider/movies/'. $home_slide->slide_image);
            if ($content) {
              unlink(public_path() . '/images/home_slider/movies/'. $home_slide->slide_image);
            }
          } else if ($home_slide->tv_series_id != null) {
            $content = @file_get_contents(public_path() . '/images/home_slider/shows/'. $home_slide->slide_image);
            if ($content) {
              unlink(public_path() . '/images/home_slider/shows/'. $home_slide->slide_image);
            }
          }
        }

        $home_slide->delete();
      }

      return back()->with('deleted', 'Slides has been deleted');
    }
}

resources/views/admin/homeslider/create.blade.php
@extends('layouts.admin')
@section('title','Create Slider')
@section('content')
  <div class="admin-form-main-block mrg-t-40">
    <h4 class="admin-form-text"><a href="{{url('admin/home_slider')}}" data-toggle="tooltip" data-original-title="Go back" class="btn-floating"><i class="material-icons">reply</i></a> Add Slide</h4>
    <div class="row">
      <div class="col-md-6">
        <div class="admin-form-block z-depth-1">
          {!! Form::open(['method' => 'POST', 'action' => 'HomeSliderController@store', 'files' => true]) !!}
            <div class="bootstrap-checkbox slide-option-switch form-group{{ $errors->has('prime_main_slider') ? ' has-error' : '' }}">
              <div class="row">
                <div class="col-md-7">
                  <h5 class="bootstrap-switch-label">Slide For</h5>
                </div>
                <div class="col-md-5 pad-0">
                  <div class="make-switch">
                    {!! Form::checkbox('', 1, 1, ['class' => 'bootswitch', 'id' => 'TheCheckBox', "data-on-text"=>"Movies", "data-off-text"=>"Tv Series", "data-size"=>"small"]) !!}
                  </div>
                </div>
              </div>
              <div class="col-md-12">
                <small class="text-danger">{{ $errors->first('prime_main_slider') }}</small>
              </div>
            </div>
            <div id="movie_id_block" class="form-group{{ $errors->has('movie_id') ? ' has-error' : '' }}">
              {!! Form::label('movie_id', 'Select Slide For Movie') !!}
              <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="Please select slide for movie"></i>
              {!! Form::select('movie_id', $movie_list, null, ['class' => 'form-control select2', 'placeholder' => '']) !!}
              <small class="text-danger">{{ $errors->first('movie_id') }}</small>
            </div>
            <div id="tv_series_id_block" class="form-group{{ $errors->has('tv_series_id') ? ' has-error' : '' }}">
              {!! Form::label('tv_series_id', 'Select Slide For Tv Show') !!}
              {!! Form::select('tv_series_id', $tv_series_list, null, ['class' => 'form-control select2', 'placeholder' => '']) !!}
              <small class="text-danger">{{ $errors->first('tv_series_id') }}</small>
            </div>
            <div class="form-group{{ $errors->has('slide_image') ? ' has-error' : '' }} input-file-block">
              {!! Form::label('slide_image', 'Slide Image') !!}
              <i class="fa fa-info-circle" data-toggle="tooltip" data-placement="top" title="Upload slide image"></i>
              {!! Form::file('slide_image', ['class' => 'input-file', 'id'=>'slide_image']) !!}
              <label for="slide_image" class="btn btn-danger js-labelFile" data-toggle="tooltip" data-original-title="slide image">
                <i class="icon fa fa-check"></i>
                <span class="js-fileName">Choose a File</span>
              </label>
              <p class="info">Choose slide image</p>
              <small class="text-danger">{{ $errors->first('slide_image') }}</small>
            </div>
            <div class="form-group{{ $errors->has('active') ? ' has-error' : '' }}">
              <div class="row">
                <div class="col-xs-3">
                  {!! Form::label('active', 'Active') !!}
                </div>
                <div class="col-xs-5 pad-0">
                  <label class="switch">
                    {!! Form::checkbox('active', 1, 1, ['class' => 'checkbox-switch']) !!}
                    <span class="slider round"></span>
                  </label>
                </div>
              </div>
              <div class="col-xs-12">
                <small class="text-danger">{{ $errors->first('series') }}</small>
              </div>
            </div>
            <div class="btn-group pull-right">
              <button type="reset" class="btn btn-info"><i class="material-icons left">toys</i> Reset</button>
              <button type="submit" class="btn btn-success"><i class="material-icons left">add_to_photos</i> Add Slide</button>
            </div>
            <div class="clear-both"></div>
          {!! Form::close() !!}
        </div>
      </div>
    </div>
  </div>
@endsection

@section('custom-script')
  <script>
    $(document).ready(function(){

      $('#tv_series_id_block').hide();

      $('#TheCheckBox').on('switchChange.bootstrapSwitch', function (event, state) {

          if (state == true) {

            $('#tv_series_id_block').hide();
            $('#movie_id_block').show();

          } else if (state == false) {

            $('#tv_series_id_block').show();
            $('#movie_id_block').hide(); 

          };

      });
      
    });
  </script>
@endsection

resources/views/admin/homeslider/index.blade.php
@extends('layouts.admin')
@section('title','Slider')
@section('content')
  <div class="content-main-block mrg-t-40">
    <div class="admin-create-btn-block">
      <a href="{{route('home_slider.create')}}" class="btn btn-danger btn-md"><i class="material-icons left">add</i> Add Slide</a>
      <!-- Delete Modal -->
      <a type="button" class="btn btn-danger btn-md z-depth-0" data-toggle="modal" data-target="#bulk_delete"><i class="material-icons left">delete</i> Delete Selected</a>   
      <!-- Modal -->
      <div id="bulk_delete" class="delete-modal modal fade" role="dialog">
        <div class="modal-dialog modal-sm">
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <div class="delete-icon"></div>
            </div>
            <div class="modal-body text-center">
              <h4 class="modal-heading">Are You Sure ?</h4>
              <p>Do you really want to delete these records? This process cannot be undone.</p>
            </div>
            <div class="modal-footer">
              {!! Form::open(['method' => 'POST', 'action' => 'HomeSliderController@bulk_delete', 'id' => 'bulk_delete_form']) !!}
                <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">No</button>
                <button type="submit" class="btn btn-danger">Yes</button>
              {!! Form::close() !!}
            </div>
          </div>
        </div>
      </div>
    </div>
    <p class="info">You can change the position of items by DRAG &amp; DROP</p>
    <div class="content-block box-body">
      <table id="full_detail_table" class="table table-hover db">
        <thead>
          <tr class="table-heading-row">
          <th>
            <div class="inline">
              <input id="checkboxAll" type="checkbox" class="filled-in" name="checked[]" value="all" id="checkboxAll">
              <label for="checkboxAll" class="material-checkbox"></label>
            </div>
            #
          </th>
          <th>Movie</th>
          <th>Tv Series</th>
          <th>Slide Image</th>
          <th>Active</th>
          <th>Actions</th>
        </tr>
        </thead>
        @if ($home_slides)
          <tbody>
          @foreach ($home_slides as $key => $home_slide)
            <tr id="item-{{$home_slide->id}}">
              <td>
                <div class="inline">
                  <input type="checkbox" form="bulk_delete_form" class="filled-in material-checkbox-input" name="checked[]" value="{{$home_slide->id}}" id="checkbox{{$home_slide->id}}">
                  <label for="checkbox{{$home_slide->id}}" class="material-checkbox"></label>
                </div>
                <a class="handle"><i class="fa fa-unsorted" style="opacity: 0.3"></i></a>
                {{$key+1}}
              </td>
              <td>{{$home_slide->movie ? $home_slide->movie->title : '-'}}</td>
              <td>{{$home_slide->tvseries ? $home_slide->tvseries->title : '-'}}</td>
              <td>
                @if($home_slide->movie)
                  @if ($home_slide->slide_image != null)
                    <img src="{{asset('images/home_slider/movies/'. $home_slide->slide_image)}}" class="img-responsive" alt="slider-image">
                  @elseif ($home_slide->movie->poster != null)
                    <img src="{{asset('images/movies/posters/'. $home_slide->movie->poster)}}" class="img-responsive" alt="slider-image">
                  @endif
                @else
                  @if ($home_slide->slide_image != null)
                    <img src="{{asset('images/home_slider/shows/'. $home_slide->slide_image)}}" class="img-responsive" alt="slider-image">
                  @elseif ($home_slide->tvseries->poster != null)
                    <img src="{{asset('images/tvseries/posters/'. $home_slide->tvseries->poster)}}" class="img-responsive" alt="slider-image">
                  @endif
                @endif
              </td>
              <td>{{$home_slide->active == 1 ? 'Active' : 'inactive'}}</td>
              <td>
                <div class="admin-table-action-block">
                  <a href="{{route('home_slider.edit', $home_slide->id)}}" data-toggle="tooltip" data-original-title="Edit" class="btn-info btn-floating"><i class="material-icons">mode_edit</i></a>
                  <button type="button" class="btn-danger btn-floating" data-toggle="modal" data-target="#{{$home_slide->id}}deleteModal"><i class="material-icons">delete</i> </button>
                </div>
              </td>
            </tr>
            <!-- Delete Modal -->
            <div id="{{$home_slide->id}}deleteModal" class="delete-modal modal fade" role="dialog">
              <div class="modal-dialog modal-sm">
                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <div class="delete-icon"></div>
                  </div>
                  <div class="modal-body text-center">
                    <h4 class="modal-heading">Are You Sure ?</h4>
                    <p>Do you really want to delete these records? This process cannot be undone.</p>
                  </div>
                  <div class="modal-footer">
                    {!! Form::open(['method' => 'DELETE', 'action' => ['HomeSliderController@destroy', $home_slide->id]]) !!}
                        <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-danger">Yes</button>
                    {!! Form::close() !!}
                  </div>
                </div>
              </div>
            </div>
          @endforeach
          </tbody>
        @endif
      </table>
    </div>
  </div>
@endsection
@section('custom-script')
<script>
  $(function(){
    $('#checkboxAll').on('change', function(){
      if($(this).prop("checked") == true){
        $('.material-checkbox-input').attr('checked', true);
      }
      else if($(this).prop("checked") == false){
        $('.material-checkbox-input').attr('checked', false);
      }
    });
  });
  var app = new Vue({});
  $('table.db tbody').sortable({
    cursor: "move",
    revert: true,
    placeholder: 'sort-highlight',
    connectWith: '.connectedSortable',
    forcePlaceholderSize: true,
    zIndex: 999999,
    axis: 'y',
    update: function(event, ui) {
      var data = $(this).sortable('serialize');
      app.$http.post('{{route('slide_reposition')}}', {item: data}).then((response) => {
        console.log(data);
        console.log('re');
        console.log(response);
      }).catch((e) => {
        console.log($(this).sortable('serialize'));
        console.log(e);
        console.log('err');
      });
    }
  });
  $(window).resize(function() {
    $('table.db tr').css('min-width', $('table.db').width());
  });
</script>
@endsection